{
 "title": "PowerFlex - 5. Storage Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "SHOW TAG VALUES FROM \"scaleio.cluster\" WITH KEY = \"cluster\""
   },
   {
    "name": "domain",
    "query": "SHOW TAG VALUES FROM \"scaleio.protectiondomain\" WITH KEY = \"protection_domain_name\" WHERE \"cluster\" =~ /^$cluster$/"
   },
   {
    "name": "pool",
    "query": "SHOW TAG VALUES FROM \"scaleio.storagepool\" WITH KEY = \"storage_pool_name\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/"
   },
   {
    "name": "storage_node",
    "query": "SHOW TAG VALUES FROM \"scaleio.storagenode\" WITH KEY = \"storage_node_name\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2><b>Storage Node Statistics</b>: $cluster</h2></center>\n<center><h3>PowerFlex Metrics</h3></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Node Read Op/s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.iops.read",
     "metric": "scaleio.sds.iops.read_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name::tag", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Node Write Op/s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.iops.write",
     "metric": "scaleio.sds.iops.write_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Node Read BW",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.bw.read",
     "metric": "scaleio.sds.bw.read_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Node Write BW",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.bw.write",
     "metric": "scaleio.sds.bw.write_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    }
   ]
  },
  {
   "title": "Read and Write IOPS per Storage Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_storage_node_name read",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": true,
       "tagk": "sds",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_node_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.iops.read",
     "metric": "scaleio.sds.iops.read_total",
     "query": "SELECT mean(\"storage_fe\") FROM \"default\".\"scaleio.storagenode.iops.read\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_node\"::tag =~ /^$storage_node$/) AND $timeFilter GROUP BY time($__interval), \"storage_node\"::tag fill(null)",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "$tag_storage_node_name write",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": true,
       "tagk": "sds",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_node::tag" ], "type": "tag" },
      { "params": [ "storage_node_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.iops.write",
     "metric": "scaleio.sds.iops.write_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    }
   ]
  },
  {
   "title": "Read and Write Bandwidth per SDS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_storage_node_name read",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": true,
       "tagk": "sds",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_node_id::tag" ], "type": "tag" },
      { "params": [ "storage_node_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.bw.read",
     "metric": "scaleio.sds.bw.read_total",
     "query": "SELECT mean(\"storage_fe\") FROM \"default\".\"scaleio.storagenode.bw.read\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_node_name\"::tag =~ /^$storage_node$/) AND $timeFilter GROUP BY time($__interval), \"storage_node_name\"::tag fill(null)",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    },
    {
     "aggregator": "avg",
     "alias": "$tag_storage_node_name write",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": true,
       "tagk": "sds",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_node::tag" ], "type": "tag" },
      { "params": [ "storage_node_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.bw.write",
     "metric": "scaleio.sds.bw.write_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Read Latency per Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_storage_node_name  Read Latency",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "device_name",
       "type": "wildcard"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_node_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.latency.read",
     "metric": "scaleio.device_avgReadLatencyInMicrosec",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Write Latency per Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_storage_node_name Write Latency",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "device_name",
       "type": "wildcard"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_node_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagenode.latency.write",
     "metric": "scaleio.device_avgWriteLatencyInMicrosec",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_node_name::tag", "operator": "=~", "value": "/^$storage_node$/" }
     ]
    }
   ]
  }
 ]
}