{
 "title": "PowerFlex - 4. SDC / Hosts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "SHOW TAG VALUES FROM \"scaleio.cluster\" WITH KEY = \"cluster\""
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"scaleio.sdc.iops.read\" WITH KEY = \"sdc_name\" WHERE \"cluster\" =~ /^$cluster$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2><b>SDC / Host Statistics</b></h2></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read Op/s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$sdc",
       "groupBy": false,
       "tagk": "sdc_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.sdc.iops.read",
     "metric": "scaleio.sdc.iops.read_userData",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "sdc_name", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Op/s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$sdc",
       "groupBy": false,
       "tagk": "sdc_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.sdc.iops.write",
     "metric": "scaleio.sdc.iops.write_userData",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "sdc_name", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Read B/W",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$sdc",
       "groupBy": false,
       "tagk": "sdc_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.sdc.bw.read",
     "metric": "scaleio.sdc.bw.read_userData",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "sdc_name", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Write B/W",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$sdc",
       "groupBy": false,
       "tagk": "sdc_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.sdc.bw.write",
     "metric": "scaleio.sdc.bw.write_userData",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "sdc_name", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Host IOPS",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sdc_name read",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$sdc",
       "groupBy": true,
       "tagk": "sdc_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sdc_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.sdc.iops.read",
     "metric": "scaleio.sdc.iops.read_userData",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "sdc_name::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "aggregator": "avg",
     "alias": "$tag_sdc_name write",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$sdc",
       "groupBy": true,
       "tagk": "sdc_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sdc_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.sdc.iops.write",
     "metric": "scaleio.sdc.iops.write_userData",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "sdc_name", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sdc_name read",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$sdc",
       "groupBy": true,
       "tagk": "sdc_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sdc_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.sdc.bw.read",
     "metric": "scaleio.sdc.bw.read_userData",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "sdc_name", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "aggregator": "avg",
     "alias": "$tag_sdc_name write",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$sdc",
       "groupBy": true,
       "tagk": "sdc_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sdc_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.sdc.bw.write",
     "metric": "scaleio.sdc.bw.write_userData",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "sdc_name", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}