{
 "title": "PowerFlex - 0. Cluster (Overview)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "SHOW TAG VALUES FROM \"scaleio.cluster\" WITH KEY = \"cluster\""
   },
   {
    "name": "cluster_id",
    "query": "SHOW TAG VALUES FROM \"scaleio.cluster\" WITH KEY = \"cluster_id\""
   },
   {
    "name": "device_group",
    "query": "SHOW TAG VALUES FROM \"scaleio.devicegroup\" WITH KEY = \"device_group_name\" WHERE \"cluster\" =~ /^$cluster$/ "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2><b>Gen2 Cluster Statistics</b> : $cluster</h2></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read IOPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.iops.read",
     "metric": "scaleio.cluster.iops.read_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "iliteral_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.iops.write",
     "metric": "scaleio.cluster.iops.write_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Read/Write Ratio",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "read",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.iops.read",
     "metric": "scaleio.cluster.iops.read_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "aggregator": "avg",
     "alias": "write",
     "currentFilterKey": "cluster",
     "currentFilterType": "literal_or",
     "currentFilterValue": "$cluster",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.iops.write",
     "metric": "scaleio.cluster.iops.write_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Read B/W",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Read BW",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.bw.read",
     "metric": "scaleio.cluster.bw.write_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Write B/W",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "Write BW",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.bw.write",
     "metric": "scaleio.cluster.bw.read_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster IOPS Totals",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Read IOPS",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.iops.read",
     "metric": "scaleio.cluster.iops.read_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "aggregator": "avg",
     "alias": "Write IOPS",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.iops.write",
     "metric": "scaleio.cluster.iops.write_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Bandwidth Totals",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Read BW",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.bw.read",
     "metric": "scaleio.cluster.bw.read_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "aggregator": "avg",
     "alias": "Write BW",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.bw.write",
     "metric": "scaleio.cluster.bw.write_total",
     "select": [
      [
       { "params": [ "storage_fe" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Cluster Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Cluster Read Latency",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "protection_domain_name",
       "type": "wildcard"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "storage_pool_name",
       "type": "wildcard"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.latency.read",
     "metric": "scaleio.device_avgReadLatencyInMicrosec",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Cluster Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Cluster Write Latency",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "protection_domain_name",
       "type": "wildcard"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "storage_pool_name",
       "type": "wildcard"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.cluster.latency.write",
     "metric": "scaleio.device_avgWriteLatencyInMicrosec",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Rebuild Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Rebuild BW",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.devicegroup.bw",
     "metric": "scaleio.cluster.bw.read_fwdRebuild",
     "query": "SELECT mean(\"rebuild\") FROM \"default\".\"scaleio.devicegroup.bw\" WHERE (\"device_group_name\"::tag =~ /^$device_group$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rebuild" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_group_name::tag", "operator": "=~", "value": "/^$device_group$/" }
     ]
    }
   ]
  },
  {
   "title": "Rebalance Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Rebalance BW",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.devicegroup.bw",
     "metric": "scaleio.cluster.bw.read_rebalance",
     "select": [
      [
       { "params": [ "rebalance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_group_name::tag", "operator": "=~", "value": "/^$device_group$/" }
     ]
    }
   ]
  }
 ]
}