{
 "title": "PowerFlex - 6. Volumes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "SHOW TAG VALUES FROM \"scaleio.cluster\" WITH KEY = \"cluster\""
   },
   {
    "name": "domain",
    "query": "SHOW TAG VALUES FROM \"scaleio.protectiondomain.iops.read\" WITH KEY = \"protection_domain_name\" WHERE \"cluster\" =~ /^$cluster$/"
   },
   {
    "name": "pool",
    "query": "SHOW TAG VALUES FROM \"scaleio.storagepool\" WITH KEY = \"storage_pool_name\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/"
   },
   {
    "name": "volume_name",
    "query": "SHOW TAG VALUES FROM \"scaleio.volume.bw.read\" WITH KEY = \"volume_name\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/ AND \"volume_name\" !~ /^[0-9a-fA-F]{16}$/ AND \"volume_name\" !~ /\\.(md|nd)$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2><b>Volume Statistics</b></h2></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Read Latency per Volume",
   "type": "timeseries",
   "description": "Average volume latency as reported from the SDC.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_volume_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "volume_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.volume.latency.read",
     "query": "SELECT mean(\"userDataSdc\")  / 1000 FROM \"scaleio.volume.latency.read\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/ AND \"volume_name\" =~ /^$volume_name$/ AND \"volume_name\" !~ /^[0-9a-fA-F]{16}$/ AND \"volume_name\" !~ /\\.(md|nd)$/ AND \"userDataSdc\" != 0) AND $timeFilter GROUP BY time($__interval), \"volume_name\" fill(null)",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name::tag", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name::tag", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "volume_name::tag", "operator": "=~", "value": "/^$volume_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Write Latency per Volume",
   "type": "timeseries",
   "description": "Average volume latency as reported from the SDC.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_volume_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "volume_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.volume.latency.write",
     "query": "SELECT mean(\"userDataSdc\")  / 1000 FROM \"scaleio.volume.latency.write\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/ AND \"volume_name\" =~ /^$volume_name$/ AND \"volume_name\" !~ /^[0-9a-fA-F]{16}$/ AND \"volume_name\" !~ /\\.(md|nd)$/ AND \"userDataSdc\" != 0) AND $timeFilter GROUP BY time($__interval), \"volume_name\" fill(null)",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name::tag", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name::tag", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "volume_name::tag", "operator": "=~", "value": "/^$volume_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Read IOPS per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_volume_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$volumeid",
       "groupBy": true,
       "tagk": "volume_id",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "iliteral_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "volume_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.volume.iops.read",
     "metric": "scaleio.volume.iops.read_userData",
     "query": "SELECT mean(\"userData\") FROM \"scaleio.volume.iops.read\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/ AND \"volume_name\" =~ /^$volume_name$/ AND \"volume_name\" !~ /^[0-9a-fA-F]{16}$/ AND \"volume_name\" !~ /\\.(md|nd)$/ AND \"userData\" != 0) AND $timeFilter GROUP BY time($__interval), \"volume_name\" fill(null)",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name::tag", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name::tag", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "volume_name::tag", "operator": "=~", "value": "/^$volume_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Write IOPS per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_volume_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$volumeid",
       "groupBy": true,
       "tagk": "volume_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "volume_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.volume.iops.write",
     "metric": "scaleio.volume.iops.write_userData",
     "query": "SELECT mean(\"userData\") FROM \"scaleio.volume.iops.write\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/ AND \"volume_name\" =~ /^$volume_name$/ AND \"volume_name\" !~ /^[0-9a-fA-F]{16}$/ AND \"volume_name\" !~ /\\.(md|nd)$/ AND \"userData\" != 0) AND $timeFilter GROUP BY time($__interval), \"volume_name\" fill(null)",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name::tag", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name::tag", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "volume_name::tag", "operator": "=~", "value": "/^$volume_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Bandwidth per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_volume_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$volumeid",
       "groupBy": true,
       "tagk": "volume_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "volume_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.volume.bw.read",
     "metric": "scaleio.volume.bw.read_userData",
     "query": "SELECT mean(\"userData\") FROM \"scaleio.volume.bw.read\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/ AND \"volume_name\" =~ /^$volume_name$/ AND \"volume_name\" !~ /^[0-9a-fA-F]{16}$/ AND \"volume_name\" !~ /\\.(md|nd)$/ AND \"userData\" != 0) AND $timeFilter GROUP BY time($__interval), \"volume_name\" fill(null)",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name::tag", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name::tag", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "volume_name::tag", "operator": "=~", "value": "/^$volume_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Bandwidth per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_volume_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$volumeid",
       "groupBy": true,
       "tagk": "volume_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "volume_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.volume.bw.write",
     "metric": "scaleio.volume.bw.write_userData",
     "query": "SELECT mean(\"userData\") FROM \"scaleio.volume.bw.write\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/ AND \"volume_name\" =~ /^$volume_name$/ AND \"volume_name\" !~ /^[0-9a-fA-F]{16}$/ AND \"volume_name\" !~ /\\.(md|nd)$/ AND \"userData\" != 0) AND $timeFilter GROUP BY time($__interval), \"volume_name\" fill(null)",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name::tag", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name::tag", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "volume_name::tag", "operator": "=~", "value": "/^$volume_name$/" }
     ]
    }
   ]
  }
 ]
}